# General arguments
model_location: '/pub/bjvela/GLA-GCN/common'
dataset: 'h36m'
keypoints: 'gt'
subjects_train: 'S1,S5,S6,S7,S8'
subjects_test: 'S9,S11'
actions: '*'
checkpoint: 'checkpoint'
checkpoint_frequency: 10
resume: ''
evaluate: 'GLA-GCN_Model.pt'
render: false
by_subject: false
export_training_curves: false

# Model arguments
stride: 1
epochs: 80
batch_size: 512
dropout: 0.1
learning_rate: 0.01
lr_decay: 0.95
data_augmentation: false
test_time_augmentation: false
architecture: '3,3,3,3,3'
causal: false
channels: 96
number_of_frames: 243

# Experimental arguments
subset: 1
downsample: 1
no_eval: false
dense: false
disable_optimizations: false
linear_projection: false
bone_length_term: true
no_proj: false
debug: false

# Visualization
viz_subject: null
viz_action: null
viz_camera: 0
viz_video: null
viz_skip: 0
viz_output: null
viz_bitrate: 3000
viz_no_ground_truth: false
viz_limit: -1
viz_downsample: 1
viz_size: 5
