# General arguments
dataset: 'surreal'
keypoints: 'gt'
checkpoint: 'checkpoint'
evaluate: 'Trained_With_Normalization/SemGCN_3DPW_14_fully_trained_jit_corrected_final.pt'
model_type: 'JIT'
test_using_train_mean_and_std: false
train_dataset: '3dpw'

# Dataset paths
path_to_dataset_h36m: /path/to/h36m_dataset
path_to_dataset_gpa: /path/to/gpa_dataset_file.json
path_to_dataset_surreal_train: /path/to/surreal_train_data.npz
path_to_dataset_surreal_test: /path/to/surreal_test_data.npz
path_to_dataset_3dpw: /path/to/3dpw_dataset_folder
data_dir: /path/to/data_directory

# Miscellaneous
num_workers: 2
print_sample: false 
save_predictions: false

# Input arguments
input_shape:
  batch_size: 64
  num_frames: null       
  num_joints: 14         
  coordinates: 2      

# Output arguments
output_shape:
  batch_size: 64
  num_frames: null       
  num_joints: 14         
  coordinates: 3

# Model info
model_info:
  flattened_coordinate_model: false
  output_3d: 'meters'
  root_center_2d_test_input: true
  normalize_2d_to_minus_one_to_one: false
  trained_on_normalized_data: true
  video_model: false


