# General arguments
dataset: 'surreal'
keypoints: 'gt'
checkpoint: 'checkpoint'
evaluate: 'Not_Trained_With_Normalization/Martinez_PoseAug_Unoptimized.pt'
model_type: 'JIT'

# Dataset paths
path_to_dataset_h36m: /path/to/h36m_dataset
path_to_dataset_gpa: /path/to/gpa_dataset_file.json
path_to_dataset_surreal_train: /path/to/surreal_train_data.npz
path_to_dataset_surreal_test: /path/to/surreal_test_data.npz
path_to_dataset_3dpw: /path/to/3dpw_dataset_folder
data_dir: /path/to/data_directory

# Miscellaneous
num_workers: 2
print_sample: false
save_predictions: false
per_joint_error: false

# Input arguments
input_shape:
  batch_size: 64
  num_frames: null      
  num_joints: 16         
  coordinates: 2      

# Output arguments
output_shape:
  batch_size: 64
  num_frames: null       
  num_joints: 16         
  coordinates: 3

model_info:
  flattened_coordinate_model: false
  output_3d: 'millimeters'
  root_center_2d_test_input: false
  normalize_2d_to_minus_one_to_one: true
  trained_on_normalized_data: false
  video_model: false
  
