# SEM-GCN Configuration File

# General arguments
dataset: 'h36m'                 # Target dataset (e.g., 'h36m')
keypoints: 'gt'                 # 2D detections to use (e.g., 'gt')
actions: '*'                    # Actions to train/test on, separated by comma, or '*' for all
checkpoint: 'checkpoint'        # Checkpoint directory
evaluate: 'SemGCN_jit_model_non_local.pt'                    # Checkpoint file to evaluate (leave empty if not evaluating)
subjects_train: 'S1,S5,S6,S7,S8'
subjects_test: 'S9,S11'
test_time_augmentation: false
model_name: 'semgcn'

# Dataset args 
remove_global_offset: true
keep_traj_first_pos: false

# Model Type Based on Input and Output
flattened_coordinate_model: false
non_video_model: true
video_model: false 
zero_center_root: true

path_to_dataset: '/dfs9/whayes/preserve/H36M_Dataset/h36m'
data_dir: '/pub/bjvela/PoseLab3D/data'

# Input arguments
input_shape:
  batch_size: 64
  num_frames: null       # Not used in SemGCN model; does not use temporal frames
  num_joints: 16
  coordinates: 2         # 2D input coordinates (x, y)

# Output arguments
output_shape:
  batch_size: 64
  num_frames: null
  num_joints: 16
  coordinates: 3         # 3D output coordinates (x, y, z)


# Model arguments
number_of_frames: 1
num_layers: 4                   # Number of residual layers
hid_dim: 128                    # Number of hidden dimensions
epochs: 100                     # Number of training epochs
num_workers: 2                  # Number of workers for data loading
lr: 0.001                       # Initial learning rate
lr_decay: 100000                # Number of steps for learning rate decay
lr_gamma: 0.96                  # Gamma value for learning rate decay
max_norm: true                  # Use max_norm clipping on gradients (true/false)
non_local: false                # Use non-local layers (true/false)
dropout: 0.0                    # Dropout rate


# Experimental arguments
downsample: 1                   # Downsample frame rate by factor
stride: 1
# Example Usage:
# To run training with this configuration, you might use:
# python run_sem_gcn.py --config config.yaml

# Additional Notes:
# - Ensure that the paths specified (e.g., checkpoint directory) exist or are correctly set.
# - Modify the parameters as needed to suit your training requirements.
